language: node_js
node_js:
  - "8"
cache: npm

stages:
  - build
  - build-image

jobs:
  include:
    - stage: build
      install: npm install
      script: npm run build
    - stage: build-image
      script: echo 'hello'
